EDUBASE=../cache/edubase.csv
COUNT=../bin/count.sh

COUNTS=\
	LA.tsv \
	TypeOfEstablishment.tsv \
	EstablishmentStatus.tsv \
	PhaseOfEducation.tsv \
	ReasonEstablishmentOpened.tsv \
	ReasonEstablishmentClosed.tsv \
	Boarders.tsv \
	OfficialSixthForm.tsv \
	Gender.tsv \
	ReligiousCharacter.tsv \
	Diocese.tsv \
	AdmissionsPolicy.tsv \
	SpecialClasses.tsv \
	TrustSchoolFlag.tsv \
	Trusts.tsv \
	SchoolSponsorFlag.tsv \
	SchoolSponsors.tsv \
	FederationFlag.tsv \
	Federations.tsv \
	FEHEIdentifier.tsv \
	FurtherEducationType.tsv \
	OfstedLastInsp.tsv \
	OfstedSpecialMeasures.tsv \
	Locality.tsv \
	Town.tsv \
	County.tsv \
	TelephoneNum.tsv \
	HeadTitle.tsv \
	HeadFirstName.tsv \
	HeadLastName.tsv \
	HeadHonours.tsv \
	HeadPreferredJobTitle.tsv \
	TeenMoth.tsv \
	TeenMothPlaces.tsv \
	CCF.tsv \
	SENPRU.tsv \
	EBD.tsv \
	FTProv.tsv \
	EdByOther.tsv \
	Section41Approved.tsv \
	SEN1.tsv \
	SEN2.tsv \
	SEN3.tsv \
	GOR.tsv \
	AdministrativeWard.tsv \
	ParliamentaryConstituency.tsv \
	UrbanRural.tsv \
	GSSLACode.tsv \
	MSOA.tsv \
	LSOA.tsv \
	BoardingEstablishment.tsv \
	PreviousLA-code.tsv \
	PreviousLA.tsv

all:	$(COUNTS)

LA.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "LA (name)" > $@

TypeOfEstablishment.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "TypeOfEstablishment (name)" > $@

EstablishmentStatus.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "EstablishmentStatus (name)" > $@

PhaseOfEducation.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "PhaseOfEducation (name)" > $@

ReasonEstablishmentOpened.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "ReasonEstablishmentOpened (name)" > $@

ReasonEstablishmentClosed.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "ReasonEstablishmentClosed (name)" > $@

Boarders.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Boarders (name)" > $@

OfficialSixthForm.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "OfficialSixthForm (name)" > $@

Gender.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Gender (name)" > $@

ReligiousCharacter.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "ReligiousCharacter (name)" > $@

Diocese.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Diocese (name)" > $@

AdmissionsPolicy.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "AdmissionsPolicy (name)" > $@

SpecialClasses.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SpecialClasses (name)" > $@

TrustSchoolFlag.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "TrustSchoolFlag (name)" > $@

Trusts.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Trusts (name)" > $@

SchoolSponsorFlag.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SchoolSponsorFlag (name)" > $@

SchoolSponsors.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SchoolSponsors (name)" > $@

FederationFlag.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "FederationFlag (name)" > $@

Federations.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Federations (name)" > $@

FEHEIdentifier.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "FEHEIdentifier" > $@

FurtherEducationType.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "FurtherEducationType (name)" > $@

OfstedLastInsp.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "OfstedLastInsp" > $@

OfstedSpecialMeasures.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "OfstedSpecialMeasures (name)" > $@

Locality.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Locality" > $@

Town.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Town" > $@

County.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "County (name)" > $@

TelephoneNum.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "TelephoneNum" > $@

HeadTitle.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "HeadTitle (name)" > $@

HeadFirstName.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "HeadFirstName" > $@

HeadLastName.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "HeadLastName" > $@

HeadHonours.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "HeadHonours" > $@

HeadPreferredJobTitle.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "HeadPreferredJobTitle" > $@

TeenMoth.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "TeenMoth (name)" > $@

TeenMothPlaces.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "TeenMothPlaces" > $@

CCF.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "CCF (name)" > $@

SENPRU.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SENPRU (name)" > $@

EBD.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "EBD (name)" > $@

FTProv.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "FTProv (name)" > $@

EdByOther.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "EdByOther (name)" > $@

Section41Approved.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "Section41Approved (name)" > $@

SEN1.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SEN1 (name)" > $@

SEN2.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SEN2 (name)" > $@

SEN3.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "SEN3 (name)" > $@

GOR.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "GOR (name)" > $@

AdministrativeWard.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "AdministrativeWard (name)" > $@

ParliamentaryConstituency.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "ParliamentaryConstituency (name)" > $@

UrbanRural.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "UrbanRural (name)" > $@

GSSLACode.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "GSSLACode (name)" > $@

MSOA.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "MSOA (name)" > $@

LSOA.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "LSOA (name)" > $@

BoardingEstablishment.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "BoardingEstablishment (name)" > $@

PreviousLA-code.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "PreviousLA (code)" > $@

PreviousLA.tsv:	$(EDUBASE) $(COUNT)
	$(COUNT) $(EDUBASE) "PreviousLA (name)" > $@


clean::
	rm -f *tsv
